language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: macisi528@gmail.com
  api_key:
    secure: GyIlqUhfxYvswfkfSvL/qhF/z1Vn26B6Ga4pvFEyDvztAqc/NwCQjqxZidPgZqXQU2QZV8LMUdCKnkArZ66ariAnGk9Q6ep7yn9U9N7sxurPEEeWZf5m0wX645qhylI7pJfP7jCF3rQ0f19TGGXlPHhR8KHAMM4OSxDVdo/ZfpDnZgYCjRY2ywxhyRgYP+yJxV+BhIyWn8w9AffTO/jqYypP02ChHlyH0VMpumFpj9AdLAXqXykIwkxtB0m76ad7CENDNc9D9e8TD9RuX1TazeGAEDa5XHBqk+3XhNAUeKS4w/qOflaO8XKU7kys6y5alXZJa8H8HyWS1NJ3esg1dGmbBjBmBsfytNvgER1uPr3tYjUE2+MJlKO73OuxuMSsKNS8pRUENIBnZs2yGnQ8XtUPsP3GVja91tXS/0Q+LVaTuBlNxkuHyULVHPfDR8Mn2YKBRs/kVjuWH2EshCTLupA7MbgdSgwWysvkVkVD9lTXWmZaYvAi6VGZVM5j2I40PXP+P5bQuIXDNiY0XFzBVFX5rJykuft+Djter16ig3TAYCczkVLHQGHyLxN3EJkv8uHLbsvydnP5CsD1GnbHX6mUZUErq/RBc/ASVQfbd93iVUbG5P8TEsbO8GSN3kjqSEgiq9ohl6LLszckZhpkQx49iFbYmKDp+qdfkwrLrLU=
  on:
    tags: true
    repo: EHDFE/ehdev-configer-scms
